# Generated by Django 3.0.6 on 2020-05-17 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(null=True, verbose_name='Idade')),
                ('hematocrit', models.DecimalField(decimal_places=15, max_digits=30, null=True, verbose_name='Hematócrito')),
                ('hemoglobin', models.DecimalField(decimal_places=15, max_digits=30, null=True, verbose_name='Hemoglobina')),
                ('platelets', models.DecimalField(decimal_places=15, max_digits=30, null=True, verbose_name='Plaquetas')),
                ('mpv', models.DecimalField(decimal_places=15, max_digits=30, null=True, verbose_name='MPV')),
                ('rbc', models.DecimalField(decimal_places=15, max_digits=30, null=True, verbose_name='RBC')),
                ('lymphocytes', models.DecimalField(decimal_places=15, max_digits=30, null=True, verbose_name='Linfócitos')),
                ('mchc', models.DecimalField(decimal_places=15, max_digits=30, null=True, verbose_name='MCHC')),
                ('leukocytes', models.DecimalField(decimal_places=15, max_digits=30, null=True, verbose_name='Leucócitos')),
                ('basophils', models.DecimalField(decimal_places=15, max_digits=30, null=True, verbose_name='Basófilos')),
                ('mch', models.DecimalField(decimal_places=15, max_digits=30, null=True, verbose_name='MCH')),
                ('eosinophils', models.DecimalField(decimal_places=15, max_digits=30, null=True, verbose_name='Eosinófilos')),
                ('mcv', models.DecimalField(decimal_places=15, max_digits=30, null=True, verbose_name='MCV')),
                ('monocytes', models.DecimalField(decimal_places=15, max_digits=30, null=True, verbose_name='Monócitos')),
                ('rdw', models.DecimalField(decimal_places=15, max_digits=30, null=True, verbose_name='RDW')),
                ('exam_covid', models.CharField(max_length=25, null=True, verbose_name='Diagnóstico')),
            ],
        ),
    ]
