# Generated by Django 3.0.6 on 2020-05-17 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200517_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='mch',
            field=models.DecimalField(decimal_places=30, max_digits=50, null=True, verbose_name='Hemoglobina corpuscular média'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='mchc',
            field=models.DecimalField(decimal_places=30, max_digits=50, null=True, verbose_name='Concentração corpuscular média de hemoglobina'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='mcv',
            field=models.DecimalField(decimal_places=30, max_digits=50, null=True, verbose_name='Volume corpuscular médio'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='mpv',
            field=models.DecimalField(decimal_places=30, max_digits=50, null=True, verbose_name='Volume plaquetário médio'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='rbc',
            field=models.DecimalField(decimal_places=30, max_digits=50, null=True, verbose_name='Glóbulos vermelhos'),
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='rdw',
            field=models.DecimalField(decimal_places=30, max_digits=50, null=True, verbose_name='Largura de distribuição de glóbulos vermelhos'),
        ),
    ]
